name: release

on:
  release:
    types:
      - created

jobs:
  build_linux_client:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.event.workflow_run.head_branch }}
      GOARCH: amd64
      GOOS: linux
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Compile
        working-directory: ./cmd
        run: |
          go build -o /tmp/gitoops-${{ env.GOOS }}-${{ env.GOARCH }} .

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG }}
          files: |
            /tmp/gitoops-${{ env.GOOS }}-${{ env.GOARCH }}
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_darwin_client:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.event.workflow_run.head_branch }}
      GOARCH: amd64
      GOOS: darwin
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Compile
        working-directory: ./cmd
        run: |
          go build -o /tmp/gitoops-${{ env.GOOS }}-${{ env.GOARCH }} .

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG }}
          files: |
            /tmp/gitoops-${{ env.GOOS }}-${{ env.GOARCH }}
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_windows_client:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.event.workflow_run.head_branch }}
      GOARCH: amd64
      GOOS: windows
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Compile
        working-directory: ./cmd
        run: |
          go build -o /tmp/gitoops-${{ env.GOOS }}-${{ env.GOARCH }} .

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG }}
          files: |
            /tmp/gitoops-${{ env.GOOS }}-${{ env.GOARCH }}
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
